config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "new", to: "games#new"
  post "score", to: "games#score"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'json'
require 'open-uri'

class GamesController < ApplicationController
  def new
    alphabet = ('A'..'Z')
    alphabet_array = alphabet.to_a
    @letters = alphabet_array.sample(10)
  end

  def score
    # 1. grab the letters from the params
    @letters = params[:letters].downcase.split
    # 2. get the submitted word from the params
    @attempt = params[:attempt].downcase


    # 5. compute the score and display it
    if is_english_word? && is_valid_word?
      @score = @attempt.length.fdiv(@letters.length) * 100
    else
      @score = 0
    end
    session[:score] = session[:score].present? ? session[:score] + @score : @score
    @current_score = session[:score]
    @message = create_message
  end

  private

  # {
  #   "found": false,
  #   "word": "hellow",
  #   "error": "word not found"
  # }
  def is_english_word?
    # 4. check if the submitted word is an english word
    url = "https://wagon-dictionary.herokuapp.com/#{@attempt}"
    api_content = URI.open(url).read
    response = JSON.parse(api_content)
    response["found"]
  end

  def is_valid_word?
    # 3. compare the letters with the submitted word
    @attempt.chars.all? do |char|
      @attempt.count(char) <= @letters.count(char)
    end
  end

  def create_message
    if is_english_word? && is_valid_word?
      "Congrats #{@attempt} is a valid word"
    elsif is_english_word? && !is_valid_word?
      "Sorry but #{@attempt} can't be built out of #{@letters}"
    elsif !is_english_word? && is_valid_word?
      "Sorry but #{@attempt} does not seem to be a valid English word..."
    else
      "Sorry but #{@attempt} can't be built out of #{@letters}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<div class="container">
  <div class="letters">
    <% @letters.each do |letter| %>
      <div class="letter">
        <%= letter %>
      </div>
    <% end %>
  </div>
  <form action="<%= score_path %>" method="post" data-turbo="false">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= hidden_field_tag :letters, @letters %>
    <input type="text" placeholder="What's your best guess?" name="attempt">
    <input type="submit" value="Play!">
  </form>
</div>

app/views/games/score.html.erb
<div class="container">
  <h1>Score</h1>
  <h3><%= @current_score %></h3>
  <p><%= @message %></p>
  <%= link_to "Try again", new_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>